/*
 * Message Board
 *
 * This is an example server for message board.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// EditMessage - 
func (s *DefaultApiService) EditMessage(id string, message Message) (interface{}, error) {
	// TODO - update EditMessage with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'EditMessage' not implemented")
}

// ListMessages - 
func (s *DefaultApiService) ListMessages() (interface{}, error) {
	// TODO - update ListMessages with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ListMessages' not implemented")
}

// Login - 
func (s *DefaultApiService) Login(credential Credential) (interface{}, error) {
	// TODO - update Login with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'Login' not implemented")
}

// PostMessage - 
func (s *DefaultApiService) PostMessage(message Message) (interface{}, error) {
	// TODO - update PostMessage with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PostMessage' not implemented")
}

// ViewMessage - 
func (s *DefaultApiService) ViewMessage(id string) (interface{}, error) {
	// TODO - update ViewMessage with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ViewMessage' not implemented")
}
