/*
 * Message Board
 *
 * This is an example server for message board.
 *
 * API version: 1.0.0
 * Contact: antony.h@riseup.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Credential struct {

	Login string `json:"login"`

	Password string `json:"password"`
}
